name: Publish

on:
  push:
    tags: [ '[0-9]+.[0-9]+.[0-9]+' ]

env:
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}
  GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

jobs:
  publish:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Publish
        run: ./gradlew publishAllPublicationsToGitLabRepository
